#!/bin/bash
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

# Check if user is root
if [ $(id -u) != "0" ]; then
    echo "Error: You must be root to run this script!"
    exit 1
fi

echo "+-------------------------------------------+"
echo "|    Manager for LNMJ, Written by jiawei    |"
echo "+-------------------------------------------+"
echo "|    https://github.com/zjw2011/lnmj             |"
echo "+-------------------------------------------+"

# PHPFPMPIDFILE=/usr/local/php/var/run/php-fpm.pid

arg1=$1
arg2=$2

lnmj_kill()
{
    # echo "Kill nginx,php-fpm,mysql process..."
    # killall nginx
    # killall mysqld
    # killall php-fpm
    # killall php-cgi
    echo "done."
}

lnmj_status()
{
	echo 'TODO'
    # /etc/init.d/nginx status
    # if [ -f $PHPFPMPIDFILE ]; then
    #     echo "php-fpm is runing!"
    # else
    #     echo "php-fpm is stop!"
    # fi
    # /etc/init.d/mysql status
}

lnmj_stop()
{
	echo 'TODO'
}

case "${arg1}" in
    start)
        lnmp_start
        ;;
    stop)
        lnmj_stop
        ;;
    restart)
        lnmp_stop
        lnmp_start
        ;;
    reload)
        lnmp_reload
        ;;
    kill)
        lnmj_kill
        ;;
    status)
        lnmj_status
        ;;
    nginx)
        /etc/init.d/nginx ${arg2}
        ;;
    mysql)
        /etc/init.d/mysql ${arg2}
        ;;
    mariadb)
        /etc/init.d/mariadb ${arg2}
        ;;
    php-fpm)
        /etc/init.d/php-fpm ${arg2}
        ;;
    pureftpd)
        /etc/init.d/pureftpd ${arg2}
        ;;
    httpd)
        /etc/init.d/httpd ${arg2}
        ;;
    vhost)
        Function_Vhost ${arg2}
        ;;
    database)
        Verify_DB_Password
        Function_Database ${arg2}
        TempMycnf_Clean
        ;;
    ftp)
        Check_Pureftpd
        Function_Ftp ${arg2}
        ;;
    ssl)
        info="n"
        Add_SSL_Menu
        Add_SSL
        ;;
    dnsssl|dns)
        Add_Dns_SSL ${arg2}
        ;;
    *)
        echo "Usage: lnmj {start|stop|reload|restart|kill|status}"
        echo "Usage: lnmj {nginx|mysql|mariadb|php-fpm|pureftpd} {start|stop|reload|restart|kill|status}"
        echo "Usage: lnmj vhost {add|list|del}"
        echo "Usage: lnmj database {add|list|edit|del}"
        echo "Usage: lnmj ftp {add|list|edit|del|show}"
        echo "Usage: lnmj ssl add"
        echo "Usage: lnmj {dnsssl|dns} {cx|ali|cf|dp|he|gd|aws}"
        ;;
esac
exit
